#!/bin/sh

# List of Resources
#	Configuration: https://sookocheff.com/post/vim/neovim-java-ide/
#	Configuration: https://alpha2phi.medium.com/neovim-for-beginners-java-6a86cf1a91a5
#	Debuggin: https://alpha2phi.medium.com/neovim-for-beginners-java-debugging-f141dc2bca96

# TODO
# - Nixify this
# - Clone repositories to ~/.local/share/nvim

cd ~/.config/nvim/java/java-debug
./mvnw clean install

cd ~/.config/nvim/java/vscode-java-test
npm install
npm run build-plugin
