return {
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Hint = "",
	},
	debugging = {
		Breakpoint = "",
		Expanded = "",
		Collapsed = "",
		Circular = "",
	},
	kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		Copilot = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
}
